name: Run PHPUnit Tests

on:
  push:

jobs:
  php-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Run
        uses: styfle/cancel-workflow-action@d07a454dad7609a92316b57b23c9ccfd4f59af66 # 0.13.1
        with:
          access_token: ${{ github.token }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          coverage: none
          extensions: readline

      - name: Checkout code
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.testing.example', '.env');"

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run unit tests
        run: ./vendor/bin/phpunit
